In [3]:
import numpy as np
import pandas as pd

In [4]:
prices_per_category = pd.Series({"Product A": 22250, "product B": 16600, "Product C": 15600})
prices_per_category

Product A    22250
product B    16600
Product C    15600
dtype: int64

In [5]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [6]:
type(prices_per_category.values)

numpy.ndarray

In [7]:
prices_per_category.array

<NumpyExtensionArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [8]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [9]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [10]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [11]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

KeyError: "['Product B'] not in index"

In [ ]:
nums = pd.Series([15, 1000, 23, 45, 444])
nums

In [ ]:
nums.sort_values()

In [ ]:
nums.sort_values(ascending=True)

In [ ]:
nums.sort_values(ascending = False)

In [ ]:
data = pd.read_csv("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S17 - pandas Series\\Location.csv").squeeze()
location_data = data.copy()
location_data.head(10)

In [ ]:
# To be used w/out squeeze() -- by = ['Location'],

location_data.sort_values( ascending = False)

In [ ]:
location_data.index

In [ ]:
location_data.name

In [ ]:
location_data.index.name

In [ ]:
location_data.index.name = 'Index'

In [ ]:
location_data.index.name

In [ ]:
location_data

In [ ]:
location_data.sort_values()

In [ ]:
location_data.sort_values().head()

In [ ]:
location_data.sort_values().tail()

In [ ]:
location_data.sort_values().index

In [ ]:
location_data.index

In [ ]:
type(location_data.index)

In [ ]:
location_data.index.to_numpy()

In [ ]:
location_data.sort_values(ascending= False)

In [ ]:
location_data_sv = location_data.sort_values(ascending= False)

In [ ]:
location_data_sv.head()

In [ ]:
location_data_sv.index

In [ ]:
location_data_sv.index.sort_values()

In [ ]:
location_data_sv.head()

In [ ]:
location_data_sv.index = location_data_sv.index.sort_values()

In [ ]:
location_data_sv

In [ ]:
location_data_sv.sort_index()
location_data_sv

In [ ]:
location_data_sv = location_data_sv.sort_index(ascending = True)
location_data_sv

In [ ]:
import numpy as np

In [ ]:
array_a = np.array([[3, 2, 1], [6, 3, 2]])
array_a

In [ ]:
pd.DataFrame(array_a)

In [ ]:
type(pd.DataFrame(array_a))

In [ ]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'])
df

In [ ]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'], index = ['Row 1', 'Row 2 '])
df

In [ ]:
data1 = pd.read_csv("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", index_col = 'LoanID')
lending_co_data = data1.copy()
lending_co_data.head()


In [ ]:
type(lending_co_data)

In [ ]:
lending_co_data.index


In [ ]:
type(lending_co_data.index)

In [ ]:
lending_co_data.columns

In [ ]:
type(lending_co_data.columns)

In [ ]:
lending_co_data.axes

In [ ]:
lending_co_data.dtypes

In [ ]:
lending_co_data.values

In [ ]:
type(lending_co_data.values)

In [ ]:
lending_co_data.to_numpy()

In [ ]:
type(lending_co_data.to_numpy())

In [ ]:
lending_co_data.shape

In [ ]:
len(lending_co_data.columns)

In [46]:
data1 = pd.read_csv("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", index_col = 'StringID')
lending_co_data = data1.copy()
lending_co_data.head()


LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_3       3  Product B           Male   Location 8  Region 3     16600.0   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   
LoanID_5       5  Product B         Female  Location 34  Region 3     21250.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_3  08/12/2016     1000         45          365       2260       3205   
LoanID_4         NaN     2200         45          365       3141       4166   
LoanID_5  28/10/2017     2200         55          365       3570       4745   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_2       16041     Active  
LoanID_3       16340        NaN  
LoanID_4       16321     Active  
LoanID_5       14720     Active

In [ ]:
lending_co_data.Product

In [ ]:
lending_co_data.Location

In [ ]:
lending_co_data['Product']

In [ ]:
lending_co_data['Location'].sort_index(ascending= False)

In [ ]:
lending_co_data[['Product']]

In [ ]:
lending_co_data[['Location']]

In [ ]:
lending_co_data[['Location', 'Product']].head()

In [ ]:
prod_loc = ['Location', 'Product']
lending_co_data[prod_loc].head()


In [ ]:
lending_co_data.iloc[1]

In [ ]:
lending_co_data.iloc[1, 3]    # Second row, fourth column

In [ ]:
lending_co_data.iloc[1, :]

In [ ]:
lending_co_data.iloc[:, 3]

In [ ]:
lending_co_data.iloc[[1, 3], :]

In [ ]:
lending_co_data.iloc[:, [1, 3]]

In [48]:
lending_co_data.loc['LoanID_3']

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [50]:
lending_co_data.loc['LoanID_3', :]

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [52]:
lending_co_data.loc['LoanID_3', 'Region']

'Region 3'

In [56]:
lending_co_data.loc[:, 'Location']


StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [58]:
data1 = pd.read_csv("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", index_col = 'LoanID')
lending_co_data = data1.copy()
lending_co_data.head()

StringID    Product CustomerGender     Location    Region  TotalPrice  \
LoanID                                                                          
1       LoanID_1  Product B         Female   Location 3  Region 2     17600.0   
2       LoanID_2  Product D         Female   Location 6  Region 6         NaN   
3       LoanID_3  Product B           Male   Location 8  Region 3     16600.0   
4       LoanID_4  Product A           Male  Location 26  Region 2     17600.0   
5       LoanID_5  Product B         Female  Location 34  Region 3     21250.0   

         StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
LoanID                                                                      
1       04/07/2018     2200         45          365       3221       4166   
2       02/01/2019     2200         45          365       3161       4096   
3       08/12/2016     1000         45          365       2260       3205   
4              NaN     2200         45          365       3141       4166   
5       28/10/2017     2200         55          365       3570       4745   

        AmtPaid360 LoanStatus  
LoanID                         
1            14621     Active  
2            16041     Active  
3            16340        NaN  
4            16321     Active  
5            14720     Active

In [66]:
lending_co_data.shape

(1043, 14)

In [68]:
lending_co_data.iloc[:,13]

LoanID
1                 Active
2                 Active
3                    NaN
4                 Active
5                 Active
              ...       
1039    Finished Payment
1040    Finished Payment
1041    Finished Payment
1042    Finished Payment
1043    Finished Payment
Name: LoanStatus, Length: 1043, dtype: object

In [70]:
lending_co_data.iloc[:,-1]

LoanID
1                 Active
2                 Active
3                    NaN
4                 Active
5                 Active
              ...       
1039    Finished Payment
1040    Finished Payment
1041    Finished Payment
1042    Finished Payment
1043    Finished Payment
Name: LoanStatus, Length: 1043, dtype: object

In [72]:
lending_co_data['TotalPrice'].iloc[0, :]

IndexingError: Too many indexers

In [74]:
lending_co_data['TotalPrice'].iloc[0]

17600.0

In [78]:
lending_co_data['TotalPrice'].loc[1]

17600.0

In [80]:
data1 = pd.read_csv("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", index_col = 'StringID')
lending_co_data = data1.copy()
lending_co_data.head()

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_3       3  Product B           Male   Location 8  Region 3     16600.0   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   
LoanID_5       5  Product B         Female  Location 34  Region 3     21250.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_3  08/12/2016     1000         45          365       2260       3205   
LoanID_4         NaN     2200         45          365       3141       4166   
LoanID_5  28/10/2017     2200         55          365       3570       4745   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_2       16041     Active  
LoanID_3       16340        NaN  
LoanID_4       16321     Active  
LoanID_5       14720     Active

In [82]:
lending_co_data['TotalPrice'].iloc[0]

17600.0

In [84]:
lending_co_data['TotalPrice'].loc['LoanID_1']

17600.0

In [86]:
lending_co_data['TotalPrice'][0]

C:\Users\brand\AppData\Local\Temp\ipykernel_17196\1605309455.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lending_co_data['TotalPrice'][0]


17600.0

In [1]:
import numpy as np


In [5]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array_a[0]

array([1, 2, 3])

In [11]:
array_a[0][1]

2

In [13]:
array_a[0, 1]

2

In [15]:
array_a[:, 0]

array([1, 4])

In [17]:
array_b = np.array([1, 2, 3])
array_b[-1]

3

In [25]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_a[0, 2] = 9 

In [29]:
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [33]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [37]:
array_a[:, 0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [41]:
list_a = [8, 7, 8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [43]:
array_a[:] = 9

In [45]:
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [47]:
array_a = np.array([7, 8, 9])
array_b = np.array([[1, 2, 3], [4, 5, 6]])

In [49]:
array_a + 2

array([ 9, 10, 11])

In [51]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [53]:
list_a


[8, 7, 8]

In [57]:
list_a + [2]

[8, 7, 8, 2]

In [59]:
array_a + array_b[0]

array([ 8, 10, 12])

In [61]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [63]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype= 'float32')
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [69]:
array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype= np.float32)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [71]:
array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [73]:
array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype= np.bool)
array_a

C:\Users\brand\AppData\Local\Temp\ipykernel_10716\3369712922.py:1: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype= np.bool)


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [75]:
array_a = np.array([[1, 2, 3], [4, 5, 6]], np.str)
array_a

C:\Users\brand\AppData\Local\Temp\ipykernel_10716\2969976451.py:1: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  array_a = np.array([[1, 2, 3], [4, 5, 6]], np.str)


AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [77]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [83]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [85]:
matrix_c = np.array([[1,2,3], [4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [91]:
np.add(array_a, matrix_c, dtype= np.float64)

array([[2., 4., 6.],
       [5., 7., 9.]])

In [95]:
np.mean(matrix_c, axis= 0)

array([2.5, 3.5, 4.5])

In [99]:
array_c = np.array([1, 2, 3])
array_c

array([1, 2, 3])

In [101]:
type(array_c)

numpy.ndarray

In [103]:
array_c.shape


(3,)

In [107]:
print(array_c)

[1 2 3]


In [109]:
array_d = np.array([[7, 8, 9], [11, 12, 13]])

In [111]:
print(array_d)

[[ 7  8  9]
 [11 12 13]]


In [113]:
array_d.shape

(2, 3)

In [115]:
array_d.shape[0]

2

In [117]:
array_d.shape[1]

3

In [119]:
array_e = np.array(13)

In [121]:
type(array_e)

numpy.ndarray

In [123]:
print(array_e)

13


In [125]:
array_e.shape

()

In [127]:
array_f = np.array([15])

In [129]:
type(array_f)

numpy.ndarray

In [131]:
array_f.shape

(1,)

In [133]:
print(array_f)

[15]


In [137]:
list_a = [1, 2, 3, 4, 5, 6]
len(list_a)

6

In [139]:
list_a = [[1, 2, 3], [4, 5, 6]]
len(list_a)

2

In [141]:
array_a = np.array(list_a)

In [143]:
type(list_a)

list

In [145]:
type(array_a)

numpy.ndarray

In [147]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [149]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [153]:
array_a.shape

(2, 3)

In [156]:
list_a.shape

AttributeError: 'list' object has no attribute 'shape'

In [158]:
len(list_a)

2

In [178]:
print(list_a)
print()
print(array_a)

[[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [160]:
len(list_a[0])

3

In [170]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [172]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [174]:
print(array_b)

[5 7 9]


In [188]:
import math
array_e = math.sqrt(array_a[1, 0])
print(array_e)

2.0


In [184]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [3]:
import numpy as np

In [7]:
lending_co_lt = np.genfromtxt("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", delimiter = ',')
lending_co_lt

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [1.0000e+00,        nan,        nan, ..., 4.1660e+03, 1.4621e+04,
               nan],
       [2.0000e+00,        nan,        nan, ..., 4.0960e+03, 1.6041e+04,
               nan],
       ...,
       [1.0410e+03,        nan,        nan, ..., 5.1430e+03, 1.6617e+04,
               nan],
       [1.0420e+03,        nan,        nan, ..., 3.4620e+03, 1.5617e+04,
               nan],
       [1.0430e+03,        nan,        nan, ..., 4.7430e+03, 1.6617e+04,
               nan]])

In [9]:
print(lending_co_lt)

[[       nan        nan        nan ...        nan        nan        nan]
 [1.0000e+00        nan        nan ... 4.1660e+03 1.4621e+04        nan]
 [2.0000e+00        nan        nan ... 4.0960e+03 1.6041e+04        nan]
 ...
 [1.0410e+03        nan        nan ... 5.1430e+03 1.6617e+04        nan]
 [1.0420e+03        nan        nan ... 3.4620e+03 1.5617e+04        nan]
 [1.0430e+03        nan        nan ... 4.7430e+03 1.6617e+04        nan]]


In [15]:
lending_co_lt = np.genfromtxt("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", delimiter = ',', dtype = np.int32)
lending_co_lt

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,  4166, 14621,    -1],
       [    2,    -1,    -1, ...,  4096, 16041,    -1],
       ...,
       [ 1041,    -1,    -1, ...,  5143, 16617,    -1],
       [ 1042,    -1,    -1, ...,  3462, 15617,    -1],
       [ 1043,    -1,    -1, ...,  4743, 16617,    -1]])

In [21]:
lending_co_lt = np.genfromtxt("C:\\Users\\brand\\Downloads\\Data Analyst Course\\S18 - pandas DataFrames\\Lending-company.csv", delimiter = ',', dtype = str)
print(lending_co_lt)

[['LoanID' 'StringID' 'Product' ... 'AmtPaid60' 'AmtPaid360' 'LoanStatus']
 ['1' 'LoanID_1' 'Product B' ... '4166' '14621' 'Active']
 ['2' 'LoanID_2' 'Product D' ... '4096' '16041' 'Active']
 ...
 ['1041' 'LoanID_1041' 'Product A' ... '5143' '16617' 'Finished Payment']
 ['1042' 'LoanID_1042' 'Product B' ... '3462' '15617' 'Finished Payment']
 ['1043' 'LoanID_1043' 'Product A' ... '4743' '16617' 'Finished Payment']]


In [23]:
lending_co_lt[0, 0] + lending_co_lt[0, 1]

'LoanIDStringID'

In [1]:
import numpy as np

In [5]:
array_empty = np.empty(shape = (2, 3))
array_empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [7.56602523e-307, 1.89146896e-307, 7.56571288e-307]])

In [11]:
array_0s = np.zeros(shape = (2, 3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
array_0s = np.zeros(shape = (2, 3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [15]:
array_ones = np.ones(shape = (2, 3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
array_full = np.full(shape = (2, 3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [21]:
matrix_a = np.array([[1,0,9,2,2], [3,23,4,5,1], [0,2,3,4,1]])
matrix_a

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [25]:
array_empty_like = np.empty_like(matrix_a)
array_empty_like

array([[4128860, 6029375, 3801155, 5570652, 6619251],
       [7536754, 6422620, 6357106, 6553710, 4259932],
       [7340144, 6357060, 6357108, 4980828, 6488175]])

In [27]:
array_zeros_like = np.zeros_like(matrix_a)
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
range(30)

range(0, 30)

In [31]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [35]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [43]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.float64)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [49]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [53]:
array_RG = gen(pcg())
array_RG.normal(size = 5)

array([ 0.40338478, -0.14060683, -1.18665083,  1.04005254,  0.38454973])

In [57]:
array_RG = gen(pcg())
array_RG.normal(size = (5,5))

array([[-0.48231223,  0.92903737,  0.49516742, -0.57246072, -3.03462642],
       [-1.13277949,  0.47775702, -0.13224205, -1.37930346, -0.0207735 ],
       [-0.80958148, -0.31181311,  1.3480276 ,  0.88414241,  1.02449183],
       [-0.44176873,  0.26124278,  2.07107427,  0.83910159, -1.28698167],
       [ 0.69482698, -1.09111696, -0.63234841,  1.59319718, -1.08442191]])

In [59]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [65]:
array_RG = gen(pcg(seed=365))
array_RG.integers(low = 10, high =100, size = (5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]], dtype=int64)

In [67]:
array_RG = gen(pcg(seed=365))
array_RG.random( size = (5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [69]:
array_RG = gen(pcg(seed=365))
array_RG.choice([1,2,3,4,5], size = (5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [71]:
array_RG = gen(pcg(seed=365))
array_RG.choice([1,2,3,4,5],  p= [0.1,0.1,0.1,0.1,0.6],size = (5,5))

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

In [73]:
array_RG = gen(pcg(seed=365))
array_RG.poisson(size= (5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]], dtype=int64)

In [75]:
array_RG = gen(pcg(seed=365))
array_RG.poisson(lam= 10, size= (5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]], dtype=int64)

In [77]:
array_RG = gen(pcg(seed=365))
array_RG.binomial(n = 100, p= 0.4, size= (5,5))

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]], dtype=int64)

In [79]:
array_RG = gen(pcg(seed=365))
array_RG.logistic(loc= 9, scale = 1.2, size= (5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

In [83]:
array_RG = gen(pcg(seed=365))

array_column_1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
array_column_2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
array_column_3 = array_RG.logistic(loc = 11, scale = 2, size = (1000))
array_column_4 = array_RG.exponential(scale = 4, size = (1000))
array_column_5 = array_RG.geometric(p = 0.7, size = (1000))


In [85]:
random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5])
random_test_data

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.43132285, 14.28873302,  3.35414141, ...,  5.44323993,
        12.1288541 , 11.53227308],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]])

In [87]:
random_test_data.shape

(5, 1000)

In [89]:
random_test_data.transpose()

array([[ 1.59077303,  6.42174295, 10.43132285,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 14.28873302,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135,  3.35414141,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  5.44323993,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.1288541 ,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.53227308,  4.86816939,  1.        ]])

In [91]:
random_test_data.shape

(5, 1000)

In [93]:
random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5]).transpose()
random_test_data.shape

(1000, 5)

In [97]:
np.savetxt("Randon-Test-from-Numpy.csv", random_test_data, fmt = "%s", delimiter = ",")

In [99]:
np.genfromtxt("Randon-Test-from-Numpy.csv", delimiter = ',')

array([[ 1.59077303,  6.42174295, 10.43132285,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 14.28873302,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135,  3.35414141,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  5.44323993,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.1288541 ,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.53227308,  4.86816939,  1.        ]])