In [1]:
import numpy as np

In [3]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_a[0:0]

array([], shape=(0, 3), dtype=int32)

In [11]:
matrix_a[0:1]

array([[1, 2, 3]])

In [13]:
matrix_a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(matrix_a[:,:])

numpy.ndarray

In [19]:
matrix_a[:1]

array([[1, 2, 3]])

In [21]:
matrix_a[1:]

array([[4, 5, 6]])

In [25]:
matrix_a[:,1:] # takes all rows, and all columns from index 1 on

array([[2, 3],
       [5, 6]])

In [29]:
matrix_a[1:,1:]  # takes all values from row index 1, and column index 1 onwards (row 2, column 2)

array([[5, 6]])

In [31]:
matrix_b = np.array([[1, 1, 1, 2, 0], [3, 6, 6, 7, 4], [4, 5, 3, 8, 0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [33]:
matrix_b[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [35]:
matrix_b[::,::]  #Start, end, step - for each row and column

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [37]:
matrix_b[::2,::]  # every other row

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [39]:
matrix_b[::,::2] # every other column

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [41]:
matrix_b[::2,::2]  # every other column and every other row

array([[1, 1, 0],
       [4, 3, 0]])

In [43]:
matrix_b[::-2,::2] # traversing the array in reverse

array([[4, 3, 0],
       [1, 1, 0]])

In [45]:
matrix_b[-1::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])

In [47]:
matrix_b[-1::-1,::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [49]:
matrix_c = np.array([[1, 1, 1, 2, 0], [3, 6, 6, 7, 4], [4, 5, 3, 8, 0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [51]:
matrix_c[:,0]

array([1, 3, 4])

In [55]:
matrix_c[:,0] > 2  #Conditional slicing

array([False,  True,  True])

In [58]:
matrix_c[:,:] > 2 

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [62]:
matrix_c[matrix_c[:,:] > 2]    # shows only the values that fit the condition

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [64]:
matrix_c[matrix_c[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [66]:
matrix_c[(matrix_c[:,:] % 2 == 0) & (matrix_c[:,:] <= 4)]

array([2, 0, 4, 4, 0])

In [68]:
matrix_c[(matrix_c[:,:] % 2 == 0) | (matrix_c[:,:] <= 4)]

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

In [70]:
matrix_d = np.array([[1, 1, 1, 2, 0], [3, 6, 6, 7, 4], [4, 5, 3, 8, 0]])
matrix_d

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [72]:
type(matrix_d[0,0])

numpy.int32

In [74]:
print(matrix_d[0,0])

1


In [76]:
type(matrix_d[0,0:1])

numpy.ndarray

In [90]:
print(matrix_d[0,0: 2:])

[1 1]


In [92]:
type(matrix_d[0:1, 0:1])

numpy.ndarray

In [94]:
print(matrix_d[0:1, 0:1])

[[1]]


In [96]:
print(matrix_d[0,0].shape)
print(matrix_d[0,0: 1].shape)
print(matrix_d[0:1, 0:1].shape)


()
(1,)
(1, 1)


In [100]:
matrix_d[0:1, 0:1].squeeze()

array(1)

In [102]:
type(matrix_d[0:1, 0:1].squeeze())

numpy.ndarray

In [104]:
matrix_d[0:1, 0:1].squeeze().shape

()

In [106]:
print(matrix_d[0:1, 0:1].squeeze())

1


In [108]:
np.squeeze(matrix_c[0:1,0:1])

array(1)

In [112]:
print(matrix_d[0,0].squeeze().shape)
print(matrix_d[0,0: 1].squeeze().shape)
print(matrix_d[0:1, 0:1].squeeze().shape)

()
()
()
